import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Login from "../components/Login/Login";
import Logo from "../components/Logo/Logo";
import Register from "../components/Register/Register";
import { registerReq } from "../src/Fetch/Auth/POSTreq";
import { Box, Button, Input, MainBox } from "../styled__components/common";

const Home: NextPage = () => {
  const [showRegister, setShowRegister] = useState<boolean>(true);
  return (
    <MainBox>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showRegister ? (
        <Register setShowRegister={setShowRegister} />
      ) : (
        <Login setShowRegister={setShowRegister} />
      )}
    </MainBox>
  );
};

export default Home;
